[workspace]
members = ["crates/libs/*", "crates/tools/*", "xtask"]
resolver = "2"

[workspace.package]
authors = ["Silitics GmbH <info@silitics.com>"]
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/silitics/rugix/"
homepage = "https://rugix.org/"

[workspace.dependencies]
# Third-party crates.
bytes = "1.7.1"
clap = { version = "4.5.24", features = ["derive"] }
console = "0.15.10"
ctrlc = { version = "3.4.5", features = ["termination"] }
flume = { version = "0.11.1", features = ["async"] }
futures = "0.3.31"
hashbrown = { version = "0.15.2", features = ["serde"] }
hex = "0.4.3"
jiff = { version = "0.2.1", features = ["serde"] }
libc = "0.2.169"
nix = { version = "0.29", features = [
    "ioctl",
    "fs",
    "mount",
    "process",
    "zerocopy",
] }
pin-project = "1.1.8"
scoped-tls = "1.0.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
sha2 = "0.10.8"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.19"
tracing = "0.1"
xz2 = "0.1.7"

# In-house crates.
si-observability = { version = "0.1.2", features = ["clap4"] }
si-crypto-hashes = { version = "0.1.2", features = ["serde", "legacy"] }
sidex = { git = "https://github.com/silitics/sidex.git" }
sidex-serde = { git = "https://github.com/silitics/sidex.git" }
xscript = { version = "0.4.0", features = ["tokio"] }

# Colocated but not Rugix-specific crates.
byte-calc = { path = "crates/libs/byte-calc", features = ["serde", "bytes"] }
reportify = { path = "crates/libs/reportify" }

# Rugix-specific crates.
rugix-bundle = { path = "crates/libs/rugix-bundle" }
rugix-chunker = { path = "crates/libs/rugix-chunker" }
rugix-cli = { path = "crates/libs/rugix-cli" }
rugix-common = { path = "crates/libs/rugix-common" }
rugix-compression = { path = "crates/libs/rugix-compression" }
rugix-fs = { path = "crates/libs/rugix-fs" }
rugix-hooks = { path = "crates/libs/rugix-hooks" }
rugix-tasks = { path = "crates/libs/rugix-tasks" }
rugix-version = { path = "crates/libs/rugix-version" }

[workspace.lints.clippy]
needless_borrows_for_generic_args = "allow"
new_without_default = "allow"

[profile.release]
# Reduce the size of the release binaries.
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"
# Ensure that any overflows will panic.
overflow-checks = true
