parent = "core/debian-trixie"

# Include recipes for the custom image.
recipes = [
    # Prepares the Raspberry Pi base image for usage with Rugix.
    "core/rpi-debian-setup",
    # Sets a static hostname (see parameters below).
    "core/set-hostname",
    # Persists the home directory of the root user.
    "core/persist-root-home",
    # Configures SSH.
    "core/ssh",
    # Install a static website.
    "hello-world",
]

[parameters."core/set-hostname"]
hostname = "rugix-template"

[parameters."core/pkg-cleanup"]
autoremove = true

[parameters."core/ssh"]
root_authorized_keys = """
<INSERT YOUR PUBLIC SSH KEY HERE>
"""

[parameters."core/rugix-ctrl"]
rugix_admin = true # Enable Rugix Admin.
